# Generated by Django 4.2.7 on 2023-11-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_alter_userprofile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
